### ISSUE TITLE
Using `send` to transfer ETH can lead to problems.

### ISSUE THREAD

**Issue by MicahZoltu** [AugurProject/augur-core#110]
There are two problems with using `send`.  The first is that its security (compared to `call`) depends on gas costs and gas refund policies being defined as they are now.  If gas cost for storage goes down significantly relative to gas cost for other operations it will be possible to alter state within the send function.  Also, if the refund policy changes such that it is possible to increase gas during operation (rather than after the transaction is complete) then it will be possible to alter state within the send function.  While both of these may be unlikely changes, they are both changes that I believe are "on the table" as far as Ethereum research goes.

The second problem is that using `send` with no gas makes it so users cannot use Augur with a non-trivial account.  The entire reason that `send`/`call` give an opportunity for the destination to execute code is to allow for interesting/complex wallet contracts.  A simple example may be a wallet contract that distributes received ETH to a couple accounts.  By giving limited gas, anyone using such a contract will lose access to their funds if they attempt to do an operation that sends ETH.  The most obvious candidate is the `cash` contract's `withdrawEther`.  A contract with an interesting receiver function will not be able to withdraw funds, but they will be able to deposit as much as they want.

The first problem is a more long-term risk that needs to be considered/assessed.  The second is a PR risk as it will allow honest participants to permanently lose access to their money.

Note: This problem exists for the `refund` call, though in that case the user will fail hard/fast rather than losing their money.  It still does preclude anyone with a certain class of smart wallet from using Augur though.

**Comment by MicahZoltu** [comment]
It is also worth noting that I don't believe the amount of gas attached to send isn't fixed at `21000` as a lot of people elude to.  Reading the details of `CALL` in the yellow paper suggests that it depends on a number of variables.

Also of note is that if the destination account doesn't yet exist (e.g., it has no state yet associated with it) then you actually need more than `21000` gas in order to complete the transfer since creating an account (first state for an address) requires over `25000` gas.  This becomes interesting when there are incentives in place to encourage clearing state, which could allow a user to effectively "delete" an account/contract until it is needed again in the future.  This is a relatively mild concern for Augur because if a user runs into this situation they can just send some ETH to the address to create it and then do their Augur transaction that sends ETH.  This could be complicated by a contract that auto-deletes itself on receipt, though that is an edge case and would require not using `send` in the first place.

My recommendation is to use `call` and supply remaining gas and ensure the code is resilient to attacks in any place where ETH is transferred.

**Comment by joeykrug** [comment]
Re the first problem, any security model is insecure against future changes where no one knows what might happen --- the security should be checked / relooked at in light of modifications to the EVM as they come up as opposed to what may or may not happen.

Regarding the second problem

> The entire reason that send/call give an opportunity for the destination to execute code is to allow for interesting/complex wallet contracts.

Isn't quite right.  Send gives an opportunity for the destination to _log_ when it receives funds.  Additionally, it should really be up to the "complex wallet contract" how to deal with the money that it receives [any solid one should be able to handle receiving money/ether, it _is_ a wallet contract after all].  If it's say a multisig contract, m of n people need to sign to send any money received, etc.  

> A simple example may be a wallet contract that distributes received ETH to a couple accounts.

The accounts can claim the received eth lazily.  Additionally, if we allow for unlimited gas spending, there'll be scenarios where transactions won't go through and there'll be unclear reasons why. 

>  A contract with an interesting receiver function will not be able to withdraw funds, but they will be able to deposit as much as they want.

Maybe, depends if the contract is written well.  

Do you have any live examples of such contracts large amounts of people are using?  If not, I'd rather take the security benefits / play it safe by using send and only address this if such a thing ever comes to pass.  

Regarding the `2300` number [from Vitalik last year after the DAO attack]:

> This is because the rules for calling specify that the child must have at least 2300 gas; it's assigned this gas automatically. Hence solidity gives 0, the child gets 2300, serpent gives 5000, the child gets 7300. I'm changing serpent to 0/2300 after this.

I remember lots of hubbub was made in the solidity community following your argument above, but all I've seen result from it is trouble [i.e. the DAO] and no benefits [as I haven't come across any of these elusive wallets that supposedly are used quite commonly].

**Comment by joeykrug** [comment]
Fixed in 7476ab4, new branch only has 1 send already implemented, remaining use will be for refunding event/market closing cost I imagine.  Current use [in cash.se] is secure against these vulnerabilities I was concerned about, and new contracts don't have a bunch of send use anymore, so went ahead and implemented this suggestion
