### ISSUE TITLE
Use an existing W-ETH contract rather than Cash.

### ISSUE THREAD

**Issue by MicahZoltu** [AugurProject/augur-core#112]
Augur should consider using an existing W-ETH contract rather than rolling its own (Cash).  Maker has a W-ETH contract that is live in production that is used by OasisDex for trading tokens, this would be a good candidate and would help reduce the amount of fragmentation in the ecosystem.

**Comment by joeykrug** [comment]
I can't find any contract source for this

https://github.com/OasisDEX/oasis/blob/master/frontend/imports/api/weth.js

**Comment by MicahZoltu** [comment]
I spoke with the Maker people.  Apparently the ETH Wrapper contract they use was deployed a long time ago and the original source and compiler used are no longer available.  They are planning on releasing a new version of W-ETH that will have permanently available source and be verifiable.  I don't know what the ETA for that is though.  :/

**Comment by joeykrug** [comment]
Closing for now, if one comes out that is actually used at scale + open source will use that
