### ISSUE TITLE
Consider changing the way tokens are used to redeem REP.

### ISSUE THREAD

**Issue by MicahZoltu** [AugurProject/augur-core#116]
At the moment, the shareTokens require controller access so that the controller can remove tokens when it executes a payout.  Instead, consider inverting the control such that one redemees tokens by transferring them to an Augur contract.  This would make it so instead of the Augur contracts being able to call in to the token contracts, the token contracts would call in to the Augur contracts on transfer.  The tokens would have a redeem function that could be called to reduce their token holdings to 0 and then use the controller to lookup and call into the markets contract which would pay out their winnings.

The reason this inversion of control is valuable is because there are currently 3 places where users store value for extended periods of time.  Those are in orders, as tokens, and as cash.  Because of this, I am of the belief that these 3 places are the prime target for attacks and currently one of the largest attack vectors is via the controller system (mutation systems is _always_ a high-risk attack vector).  By making it so cash and tokens are not subject to the mutation system (or if they are it is via a _much_ more rigorous process) it makes it so users are always in control of their assets except for during times of interacting with Augur.  If the controller system is somehow compromised (e.g., via hostile takeover of REP) then users can simply hold their assets and wait until the situation is fixed/resolved.

If cash and tokens are well isolated from the rest of the system (the system can't reach into either of them) then the impact of any security vulnerabilities is _much_ lower.  The biggest risk at this point would be the ETH being held by the market contract (still a pretty big risk) but I suspect that could similarly be isolated from the rest of the system.

This is all driving at the fact that there are some parts of the system that are more critical and have higher impact of failure and I question whether having a single global governance system is the right answer to the problem.  I recognize that there is a desire to be able to iterate rapidly, but some changes _should_ sit for 6-months in a pending state before being accepted while others should be allowed to go through quickly.  The cash wallet for example should require a _massive_ audit for any changes while the reporting system isn't as critical to have tight control over.

**Comment by joeykrug** [comment]
The desire isn't really to iterate rapidly on features but rather to fix bugs / vulnerabilities rapidly

I like this idea re control of tokens inversion, although the shares need to be mutated during taking of orders as well which would make changing this much more complex imo [and trading is already complicated enough]. Any change made to shares [ignoring maliciousness of the Augur dev team, which is not a consideration during the first few months post initial launch, later on it'll switch to the time intensive decentralized updating system] would allow for plenty of time to get rid of shares via complete sets before the new contract is in
