### ISSUE TITLE
Contracts should use indivisible units of currency _EVERYWHERE_

### ISSUE THREAD

**Issue by MicahZoltu** [AugurProject/augur-core#119]
There are some places where functions expect a divisible unit of currency as input.  To minimize the chance of bugs, the contracts should _never_ interface with anything other than indivisible units of currency.  An example of where this pattern is not followed is in `placeOrder`, whose input is in a _variable_ unit (based on currency decimal places).  The entire Augur system (including UI/middleware) should be using base units only and humanizing only when displaying to the user or receiving as input from the user.

In my experience, not using consistent units throughout an application is a leading cause of bugs and I would consider this inconsistency to be a major concern.

**Comment by joeykrug** [comment]
The amount in place order *is* in base units _of the currency the order is placed in_.  If a currency has 9 decimal places then ONE is 10**9 instead of 10**18

**Comment by MicahZoltu** [comment]
The comment says:
> price is always in 10^18 fxp, amount is in the market's currency # of decimals, e.g. for 9 10^9 is 1 share [so buy 10**9 complete sets and it'll cost you 1 full unit of that currency or buy 10^9 at a fxpPrice of 10^18 it'll cost you 1 full unit of the currency]

To me this means that `fxpAmount` of `1` means `10^18 Wei`.  Is this interpretation of the comment incorrect?

**Comment by joeykrug** [comment]
Yeah it is, I'll edit the comment and post it here again

**Comment by MicahZoltu** [comment]
The same comment also says:
> smallest order value is 0.00000001

Which further suggests to me that something isn't happening in some currency's base unit (or the comment is wrong).

**Comment by joeykrug** [comment]
Clarified description in 0d581b2

Rest of this is applicable in #136
