### ISSUE TITLE
Create Logs

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur-core#12]
Logs need to be created for contracts to provide useful data to UI

**Comment by scottzer0** [comment]
thanks for this code, jack.  

the callback use case should not be implemented as a log entry.   this issue should be a backlog issue until the use cases come up.

**Comment by joeykrug** [comment]
callbacks don't work for _all_ transactions on the network... I don't get the result from Jim's callback in Texas after he buys some shares

**Comment by joeykrug** [comment]
Added logs for market pricing --- closing now --- open a new issue if any further logs wanted or reopen this one w/ a comment
