### ISSUE TITLE
ERC20 is incorrectly implemented.

### ISSUE THREAD

**Issue by MicahZoltu** [AugurProject/augur-core#120]
In a few places I see mention of `decimals` in relation to ERC20 tokens.  However, ERC20 does not include decimals.  It was discussed but in the end it was intentionally left out of ERC20 (for incredibly valid reasons).  If Augur wants to be compatible with ERC20 tokens it should not assume that they will have a `decimal` on them.

The actual signature for an ERC20 token is:
```
ERC20: [
	allowance:[address,address]:uint256,
	approve:[address,uint256]:bool,
	balanceOf:[address]:uint256,
	totalSupply:[]:uint256,
	transfer:[address,uint256]:bool,
	transferFrom:[address,address,uint256]:bool
]
```

**Comment by joeykrug** [comment]
- ERC20 is a draft and non final proposal
- The vast majority of the community uses decimals
- https://ethereum.org/token [even Ethereum's website]
- Mist requires decimals to be specified for an erc 20 to work within the UI
- AFAIK Augur doesn't assume any ERC20 tokens have decimals on them [beyond its own, which do --- the top 2 tokens on etherscan also have decimals, didn't check further]

So by a practical sense of the standard [as in usage, what clients support, etc.] I'd say it's correctly implemented.  The standard also does not prohibit _additional_ features, it only requires that an ERC20 token has those bare minimum functions stated above.

If there are any places in augur where we *do* assume erc20 tokens have decimals, then that is valid trouble / an incorrect implementation

**Comment by MicahZoltu** [comment]
This is the primary culprit, though I recognize that the script is incomplete so may be subject to change: https://github.com/AugurProject/augur-core/blob/master/load_contracts2.py#L53

I agree that `decimals` is common.  However there are strong arguments (IMO) that decimals **SHOULD NOT** be part of the spec and (if I get my way) they will be excluded from any token spec.  Mist is broken if they don't work without decimals (though this fact doesn't surprise me).

Political debate aside, so far I haven't seen decimals referenced anywhere other than Augur contracts (which is fine), I'll keep my eyes out though.
