### ISSUE TITLE
The current mechanism for blocking cash withdraws isn't effective.

### ISSUE THREAD

**Issue by MicahZoltu** [AugurProject/augur-core#123]
Attack steps:
1. (block 1) Deposit 1 WEI.
2. (block 2) Initiate a withdraw of 1 WEI.
3. (block 3-n) Wait 3 days.
4. (block n+1) Execute attack that results in you getting 10^24 WEI worth of cash.
5. (block n+2) Withdraw of 10^24 WEI.

**Comment by joeykrug** [comment]
Good catch, it's missing the balance to check, very nice find

**Comment by MicahZoltu** [comment]
The simple solution here is to store the amount of Wei one attempts to be withdrawn along with the timestamp.  This creates a problem where a user can only initiate one withdraw every 3 days, so if they earn more 1-day in, they have to wait 5 days before they can withdraw that.

To solve the second problem, the contract could store an array of pending withdraws (each with timestamp + amount).  This will, of course, increase gas costs of the user (each call to withdraw will add another entry).  It also creates a problem if the user attempts to withdraw the same funds twice (perhaps they tried 1-block short of 3 days).  This could be worked around with some logic in the contract that tries to determine whether the withdraw is a retry of a previous amount or a new one, perhaps by checking if both withdraws would result in more than the total available.

Another solution would be to have separate methods for initiate and withdraw, this would solve the last issue mentioned above.

Of course, my personal opinion is to just make this a standard wrapped ETH contract with no delay on extraction.  :)

**Comment by joeykrug** [comment]
Implemented a solution that solves the main problem by including value/amount, the same amount twice is not allowed, and this machinery / delay will be removed fairly soon after launch provided things go well
