### ISSUE TITLE
Make whitelist checking consistent.

### ISSUE THREAD

**Issue by MicahZoltu** [AugurProject/augur-core#125]
`self.controller.checkWhitelist(msg.sender)` is currently used in two different ways: as something that throws if the sender isn't in the whitelist and to return true or false depending on whether the user is in the whitelist.

In most cases, the throw is the more secure option because it creates a consistent block and doesn't rely on the caller correctly interpreting the return value (no risk of forgetting a `!`).  However, there are a number of places where the method is callable publicly in which case a mutex is taken out and if it is called internally no mutex is acquired.

## Recommendation

Have `self.controller.checkWhitelist(msg.sender)` throw, as it does now and extract out all public methods into simple entry points.  Example would look something like:
```
def publicCloseMarket(market, sender):
    refund()
    MUTEX.acquire()
    result = closeMarket(market, sender)
    MUTEX.release()
    return result

def closeMarket(market, sender):
    self.controller.checkWhitelist(msg.sender)
    ...
```

This pattern, if followed liberally, will make it very clear where the public entry points are and make auditing easier.  It will also ensure that `MUTEX.release()` is called for all return paths, rather than having to rely on all return paths for a function calling release (because there is only a single return point from the public method).  For auditors, this will also make it easier to see which methods are public (particularly if a consistent naming pattern is used for the public methods).

An alternative solution would be to have a mechanism for whitelist checking that returns a value instead of throws.  This is not quite as robust of a solution because it is easy for the caller to forget a `!` (or add a `!`) and the whitelist check now is no longer doing what it is supposed to.

**Comment by joeykrug** [comment]
Note to self: when implementing this also check and see if there's any places mutexes aren't being used but should after latest contract updates.

Am going to follow the recommendation

**Comment by AlexeyAkhunov** [comment]
Ideally, there should be a way to annotate private functions in a way that compiler does not even create entry points for them. I assume that serpent does not support this?

**Comment by joeykrug** [comment]
There's a way to do this with an internal() but it doesn't solve this problem. Solidity has the same issue, which is functions need to be whitelisted to only allow other specific contracts to call them.

**Comment by joeykrug** [comment]
Most done by Jack, last one done in 95c8156c05261888a1c7fa01ee39414929ae978b
