### ISSUE TITLE
Remove REP faucet.

### ISSUE THREAD

**Issue by MicahZoltu** [AugurProject/augur-core#127]
Similar to the cash faucet, the Augur contracts should not have test code in them as this makes auditing difficult and can allow for subtle bugs once they are removed.

Recommend creating a faucet contract (not part of augur-core) and have test chains do an initial REP distribution entirely to that faucet contract.  This way, the faucet isn't part of the security critical augur contracts, but reporting beta testing can still occur.

**Comment by joeykrug** [comment]
Added in 6c90f88

**Comment by MicahZoltu** [comment]
I think we should leave this issue open so we don't forget to remove the code at launch and accidentally launch into it.

**Comment by nuevoalex** [comment]
I think this one is covered now mostly, although the contract upload will need to be aware of this.

**Comment by MicahZoltu** [comment]
Yeah, this is done.
