### ISSUE TITLE
Cost per Reporter should not be a static number.

### ISSUE THREAD

**Issue by MicahZoltu** [AugurProject/augur-core#132]
As the price of ETH fluctuates with time, so should the cost for reporting.  If ETH goes to the moon, Augur fees will similarly go to the moon.

Ideally, the cost for reporting should fluctuate such that it guarantees security by keeping REP value targeted at over 2x outstanding interest across all markets.  This would of course require a REP price feed oracle.  A price feed Oracle could be built into Augur, but that is a pretty large change.  Perhaps for launch we can figure out some simpler alternative that gets Augur "close" but is better than hard-coding the reporter fees?

At current exchange rates, if I'm doing my math right, the base fee is $3.5 per report.  This seems obscenely high to me seeing as how reporting is expected to only take a few minutes.

**Comment by joeykrug** [comment]
This is cost to cover the gas fees, not labor fees

**Comment by MicahZoltu** [comment]
In `createEvent`:
```
minFee = safeFxpMul(safeMul(safeMul(COST_PER_REPORTER, baseReporters), tx.gasprice), BRANCHES.getCurrencyRate(branch, currency))
```

Are you saying that `minFee` here is just how much reporters will have to pay in gas to report?

**Comment by joeykrug** [comment]
RIght
