### ISSUE TITLE
createMarket and createEvent don't align on fee structure.

### ISSUE THREAD

**Issue by MicahZoltu** [AugurProject/augur-core#134]
At the moment, it costs more to create an event with `createMarket` than with `createEvent`.  This means that someone not using the UI can create events that effectively don't pay reporters.

On the topic of fees, at the moment `createMarket` fees are structured oddly, seemingly as a mechanism to put upward pressure on fees.  I believe that there is value instead in ensuring that reporters get paid fairly regardless of market volume (e.g., epsilon volume markets should still result in reporters getting paid).  The formula should also (IMO) allow for 0% fee markets, which is perfectly fine if the reporters are getting paid fairly via base fee.

I recognize that this is a non-trivial problem to solve, but I'm concerned with the market dynamics created by the current formula as it incentivizes the market creator to create a market with fees as high as the market will bear even if the creator doesn't care about fees themselves.  Similarly, there is an odd downward pressure depending on how many people are competing to create markets.  This will result (I suspect) in Augur starting with very high fee markets when there is minimal market creation competition, which will hurt Augur's initial launch prospects.

**Comment by joeykrug** [comment]
Corrected for in new fee framework
