### ISSUE TITLE
Don't special case pegged currencies.

### ISSUE THREAD

**Issue by MicahZoltu** [AugurProject/augur-core#135]
The contracts need to be able to handle variable exchange rate currencies, so a mechanism has been built to handle this.  ETH pegged currencies (like Cash or W-ETH) are a subset of variable rate currencies (they can be seen as variable rate with a current rate that always returns 1).  I recommend removing all of the code that adds special handling for pegged currencies and instead require there to _always_ be a rate contract.  For Cash/W-ETH this contract would be one function big (`def rateFunction(): return(1)`).

The reason for this change is that it will reduce overall complexity of Augur by using the same mechanism for all currencies rather than having special case logic for some subset of currencies which could be handled by the existing logic.

**Comment by joeykrug** [comment]
No longer needed w/ eth only creation fees
