### ISSUE TITLE
Remove fix/unfix macros and associated functions (`float.sem`).

### ISSUE THREAD

**Issue by MicahZoltu** [AugurProject/augur-core#136]
The presence of these macros is an indicator of a problem.  The contracts should _all_ be using WEI for everything.  Given that, the contracts should have no notion of fixed-point/floating-point/decimal numbers as everything is an integer and should be treated as such in the contracts.  If a contract ever finds itself calling `unfix` or `fix` then the author is doing something wrong and they should not be given the tools to shoot themselves in the foot.

The functions in `float.sem` are similarly problematic because they cause the author to think in decimal terms which is _not_ how things actually work.  If you want to divide a number in half, you simply divide by 2, you do not multiply by 0.5 (0.5 isn't a thing in integer math).  To maintain consistency throughout the codebase trading fees (and similar) should not be denominated in percentages, they should instead be denominated as a divisor.  e.g., `tradingFee = 0.01` should really be `tradingFeeDivisor = 100`.

The goal with such a change would be to bring some consistency to the code.  In particular, integer math everywhere, no fixed point math anywhere.  Having a mix requires the reader mentally switch back and forth between the two and it requires that the author use the correct type of math for any given problem.  This puts a fairly high cognitive load on the author/auditor to get right.

**Comment by joeykrug** [comment]
If you don't have functions like safeFxpMul(a, b) then you have things like a * b / ONE --- it rapidly gets insanely more complicated as this goes on.  In fact, the Zeppelin guys were the ones who recommended we encapsulate this into this sort of thing.  "Why do you have to divide by one? Isn't that just doing nothing?"

I don't think fix/unfix are used anywhere besides one of the faucets.

Can please some people some of the time, can't please all the people all of the time.  I don't think there is any solution to this that will make people happy

**Comment by MicahZoltu** [comment]
My argument is that if you ever find yourself wanting/needing to do `a * b / ONE` in a contract then _that_ is the problem.  My problem isn't with the macros specifically, it is with the fact that code exists that can benefit from them.

In what situation do you find yourself wanting/needing to do `a * b / ONE`?  See the `tradingFee` vs `tradingFeeDivisor` argument above.  I'm arguing that integer math should be used consistently everywhere in the code rather than using fixed point math in some parts and integer math in other parts.

**Comment by joeykrug** [comment]
Whenever you multiply two integers like amount and price

**Comment by MicahZoltu** [comment]
In that example (amount * price) the problem is that `price` is denominated in ETH instead of WEI.  When I say "Everything should be in WEI" I really mean __everything__.

**Comment by joeykrug** [comment]
Price is denominated in wei

**Comment by joeykrug** [comment]
a price of 1 is 1 wei

**Comment by joeykrug** [comment]
a price of 10**18 is 1 eth

**Comment by MicahZoltu** [comment]
Ah, so the problem then is that price is actually a percentage when it should be a divisor (percentages aren't a thing in integer math).

For example, if `price` in fixed point is `0.5` then instead of passing `price = 0.5 * 10^18` into the contracts you should be passing in `priceDivisor = 2`.  The result is your code now reads `amount / priceDivisor`.  This allows the contracts to do integer math throughout instead of having to rely on fixed point math in some places and integer math in others.  In the case of things that can go above 1, you probably want a `priceMultiplier` as well so the formula would be `(amount * priceMultiplier) / priceDivisor` (parenthesis included for clarity only, I believe serpent has proper order of operations).

**Comment by joeykrug** [comment]
That seems quite confusing too tbh, using consistent fixed point would be better imo.

Also, doing it the way above a la amount / priceDivisor results in more inaccuracies since serpent rounds down.

**Comment by MicahZoltu** [comment]
> amount / priceDivisor results in more inaccuracies since serpent rounds down

Hmm, I won't claim to be an expert on the math, but doesn't `amount * (0.5 * 10^18) / 10^18` result in exactly the same thing?  In both cases you are dividing and rounding will occur at the end.

Also, fixed point math runs into problems with very large numbers.  For example, imagine someone creates a currency with 2^256 indivisible units (no reason not to).  If someone holds a significant share of that currency you cannot safely multiply it by 0.5.  In fact, any number larger than ~10^59 (I think) can't really be worked with as fixed point encoded in 256-bit integers.

**Comment by joeykrug** [comment]
Per your issue on ERC20 someone can't own a currency with that many units anyway ;) [jesting a bit here haha].

Will dig back into this once I have my tests written

**Comment by joeykrug** [comment]
Note: 

- markets need precision in description or on chain
- markets need min / max in their currency num of decimals for price to be in currency and amount of shares to just be base units
- tradingFee is other complication

**Comment by joeykrug** [comment]
No longer using fix / unfix
