### ISSUE TITLE
Provide users with a deterministic build system and verifiable contracts.

### ISSUE THREAD

**Issue by MicahZoltu** [AugurProject/augur-core#137]
Due to the multi-step process by which Augur contracts are compiled, the source code in this repository will not align with the contracts that are uploaded to the blockchain.  In order for users to be able to verify that the code Augur is running is in fact the code in this repository, a deterministic build process should be setup (Docker is an excellent candidate for this) that allows user to regenerate the code that is actually uploaded to the chain.  The outputs of this build process should include both the post-processed source files and the contract bytecode that is uploaded to the chain.

**Comment by joeykrug** [comment]
`python upload_contracts/upload_contracts.py -s src/ -c "0xmainnetControllerAddress"` allows part of this, remaining part is the compiled bytecode

**Comment by joeykrug** [comment]
Added in 1fe14eb
