### ISSUE TITLE
Implement fork resolution.

### ISSUE THREAD

**Issue by MicahZoltu** [AugurProject/augur-core#139]
Currently fork resolution is deterministic, and not actually resolving (just randomly picking).  This needs to be based on some real market.  Since EtherEx is dead, I recommend using EtherDelta (possibly dying since developer was hired onto FirstBlood.io) or OasisDex (currently the most actively developed Dex).  0x may be an option eventually, but I think it is too soon to use it (no implementations yet).

**Comment by joeykrug** [comment]
Should be in PR #150
