### ISSUE TITLE
Claiming rep is susceptible to attack

### ISSUE THREAD

**Issue by MicahZoltu** [AugurProject/augur-core#140]
1. Transfer 1 attorep to an account
2. Approve `reporting.se` for 2^256 attorep
2. call `claimInitialRepFromContract`
3. transfer 1 attorep to the same account
4. call `claimInitialRepFromContract`
--> Notice that `numberReporters is now += 2
Repeat to make numberReporters as large as you want, the only meaningful cost is gas.

The function also has a problem where a legitimate user that claims rep, then acquires more and claims that will have their first claim overwritten by their second claim, effectively burning the REP.

**Comment by joeykrug** [comment]
Fixed in e36769be7d83f97f2363a1ed7b5e79cc5ac09127
