### ISSUE TITLE
Create two branches in a fork and abandon original branch.

### ISSUE THREAD

**Issue by MicahZoltu** [AugurProject/augur-core#143]
This is related to #138 (Create ERC20 Token wrapper for reputation).  In order for a fork to correctly represent both options, the two options need to start on even footing.  At the moment, when a fork occurs reputation is copied onto a new branch and remains on the current branch.  However, the current branch _already_ has a token available, listed and traded for it while the new branch has no such token listed on any markets.  This means that _all_ liquidity and trading volume starts out backing the original fork and the competing fork needs to not only convince exchanges to list the token (there is limited time available to make this happen and this process is often slow) but it also needs to then drive enough liquidity to the market to get an accurate price representation.  On top of that, the original branch will have a familiar name (e.g., be favorited by people, watched, etc.) while the new token will be mostly unknown to most traders who aren't following Augur's forking.

To resolve this, I recommend making it so that when a fork occurs two _new_ branches are created and two _new_ tokens are created to wrap those branches.  This way, both tokens start on equal footing in the market and even if people continue to trade the original branch of REP, the market can correctly determine the value of the two new branches independent of trades occurring on the old branch.

This also has the benefit of allowing traders the option of "abstaining" from the vote by staying on the old branch until the last minute and then moving to the dominate branch when the time comes.  Following this strategy right now will result in them effectively "picking a side" even though they really want to abstain.

**Comment by joeykrug** [comment]
Reporters aren't forced to "pick a side" in the current system either, only traders and market/event creators are

**Comment by MicahZoltu** [comment]
As I understand it, a participant is unable to trade REP without picking a side in the current system.  By engaging in any kind of trade (buy or sell) you are picking a side.  What I am proposing is enabling people to continue trading REP _without_ picking a side.  This will allow someone who simply wants to exit their REP holdings (or enter the REP market) during a fork to do so without requiring that they be a participant in the market-voting mechanism.

For example, an Augur fork could result in a lot of publicity that causes new people to enter the market.  They may not realize that by buying REP they are actually voting for no-fork.  Their intent was simply to buy some REP because they think now is a good time to buy into Augur.

Similarly, an Augur fork could result in a bit of a scare causing people who don't understand the market-voting system to sell their shares, causing sharp decline in REP value.  This sharp/sudden decline could start a Kensyian beauty contest type result as people mis-interpret it as the majority voting against no-fork, when in reality it is just REP value decreasing due to market uncertainty.

**Comment by MicahZoltu** [comment]
This is a bit of a large change but I think it may resolve this problem as well as make the contracts easier to audit and allow for full REP liquidity throughout forking events.

### At all times:
* REP is tradeable on exchanges.
* REP-A is tradeable on exchanges (though volume will likely be 0 most of the time)
* REP-B is tradeable on exchanges (though volume will likely be 0 most of the time)

### When there is no active fork happening:
* REP is exchangeable for (both ways) Active-REP at a 1:1 peg (barring commit/reveal lockouts).
* REP-A ___OR___ REP-B (whichever won the last fork) is exchangeable _TO_ Active-REP at a 1:1 peg.

### When a fork starts:
* REP-A and REP-B are reset to 0.
* Any REP-A/REP-B that wasn't exchanged for REP in the previous non-fork window is lost.

### When a fork is actively happening:
* Converting between REP and Active-REP is disabled (both ways).
* Active-REP is exchangeable _TO_ REP-A or REP-B (one means left branch, other means right branch) at a 1:1 peg (barring commit/reveal lockouts).

This system solves a few problems:
1. It allows REP trading to remain liquid at all times.  There is no lockout for trading rep.
2. It allows exchanges to list 3 tokens once at Augur launch and never have to worry about listing new tokens during an Augur fork.
3. It evens the playing field between fork and no-fork, since REP-A and REP-B are equivalent to each other and neither will have any meaningful trading happening before/after a fork (all volume for both is during fork).
4. I believe it will simplify the contracts quite a bit from a security/auditing perspective.  The 3 exchange-listed tokens will be very basic/simple with the only integration point with the rest of the Augur system being the 2-way peg, which can be encapsulated into a single function in each contract (`if self.controller.whitelist(msg.sender): createTokens(address, attorep)`).  The lockout logic can be constrained to just when exchanging Active-REP (not a token) for one of the other three, it doesn't need to deal with also locking out trading of any tokens.

IMO, the big wins from this are the 2 followed by 4.  1 may be meaningful, but I'm not sure trading lockouts are ever long enough for people to care.  3 is also pretty important IMO, but it is less critical than solving the exchange listing problem.

**Comment by joeykrug** [comment]
Also if you *sell or buy* rep then yes you're picking a side.  But the same goes for the rep you get in your scenario with parent & 2 childs.  Either way you're effectively picking a side when you make a decision to buy any asset.  If you're saying you could buy parent rep and then claim on both children and then sell whichever loses eventually, yeah you could do that, although you could also just buy both sets of rep.  The exchanges want to allow trading forked rep, I can ask them about it, I imagine they'd find 3 sets of rep in a fork scenario more complicated than 2 [which also more represents how forking works in other blockchain systems]
