### ISSUE TITLE
Use delegate call everywhere instead of allowances for token transfers.

### ISSUE THREAD

**Issue by MicahZoltu** [AugurProject/augur-core#158]
Right now there are a number of places in the code (at least in the new reporting code) where an allowance is expected to be set prior to the call.  Instead, we should just do `token.transfer(... call=delegate)` so the user doesn't have to do two steps.

**Comment by tinybike** [comment]
There are a number of places in trading where I'd like to do this as well, if manually calling `approve` isn't a necessary part of the security model.

**Comment by joeykrug** [comment]
Feel free to try this. It won't work since delegate call edits storage in the caller not callee- reopen if you can get it to work
