### ISSUE TITLE
Events (logs) should be defined on data_api contracts

### ISSUE THREAD

**Issue by tinybike** [AugurProject/augur-core#159]
There are several events that are defined on contracts in the functions folder.  To make the functions contracts more easily upgradeable, they do not store their own on-contract data; instead the data is stored on the contracts in the data_api folder.

Proposing that events should also be defined on (and triggered by, via a wrapper function) the data_api contracts.  There are two reasons for this:
1. Events are also a way of storing data persistently on-chain, so to be consistent they should be grouped other data setters.
2. The originating contract address must be provided to look up logged events.  If this address can change (due to a functions contract being upgraded), a non-trivial amount of code will have to exist to handle this in the middleware/UI.

**Comment by joeykrug** [comment]
Fixed
