### ISSUE TITLE
README improvements

### ISSUE THREAD

**Issue by tinybike** [AugurProject/augur-core#163]
Some higher-level, general-purpose information about the contracts should go in the README.  A few possible things to include might be:
- explain what the three src folders we use (data_api, functions, extensions) are / why they're organized that way
- explanation (maybe even a diagram?) of the dependencies between contracts
- overview of our security model, including a description of what the controller and mutex contracts do and why they're important
- explanation of why we use Serpent instead of Solidity (and a link to the Serpent wiki for interested parties)
- explain what the contract loader is and how it works
- explanation of what the API maker scripts are
- instructions for how to run our test suite (+ explanation of the pyethereum tester environment the tests run in)
- instructions for how to upload our contracts to a real chain

**Comment by joeykrug** [comment]
Also add a link to https://github.com/beaugunderson/serplint from our readme for those wanting to lint / check their serpent code.

**Comment by janani-sridhar** [comment]
When do you want this by?

**Comment by joeykrug** [comment]
Next 10 days or so would be good

**Comment by joeykrug** [comment]
Fixed in #212 by @janani-sridhar
