### ISSUE TITLE
front running protection `tx.gasprice`

### ISSUE THREAD

**Issue by sophiii** [AugurProject/augur-core#203]
﻿# Issue Template
### Brief Description
https://github.com/AugurProject/augur-core/commit/48d6487d8e18597e644bf7f2d260e1ee7d490e43 introduced a `gasPrice` limit on transactions to prevent an attacker from front running an already broadcast transaction with higher gas. 

Limiting the `gasPrice` is insufficient in some cases geth only caches ~ 1000 unconfirmed transactions. so an attacker could create 1000 transactions with a higher gas price and purge the victims TX from the cache and then broadcast their own with acceptable gas limit. 

Also miners que transactions in order of gasPrice , but if `gasPrice == gasPrice` then they order them randomly, which means that the protection you offer against frount running here can be undone with Sybil attacks. 

### Reproduction Steps
1. Victim broadcast a tx `saveOrder`.
2. Attacker broadcast many tx `saveOrder` from different accounts.
3. Attacker gets into a block first due to miners randomly ordering equal gasPrice transactions. 

### Expected Results
Victim should get in a a block first. 

### Actual Results
attacker gets in block first. 

### Proposed Solution
Use a commit reveal order system.

**Comment by MicahZoltu** [comment]
Excellent find @sophiii.  We have started discussing this in Augur slack #dev if you want to share any additional thoughts.

**Comment by joeykrug** [comment]
Removed gasprice mechanism due to OP
