### ISSUE TITLE
Make tests cwd-agnostic

### ISSUE THREAD

**Issue by beaugunderson** [AugurProject/augur-core#207]
Currently they must be executed from `tests/`.

Discussion [here](https://augurproject.slack.com/archives/C031NRD9B/p1498590987066235).

**Comment by beaugunderson** [comment]
(I'm working on this now but can't assign myself)

**Comment by MicahZoltu** [comment]
Wasn't auto-closed since changes are on reporting branch.  Will close since that will merge eventually.
