### ISSUE TITLE
A couple things to keep in mind for sorting and markets denominated in other markets

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur-core#219]
- for markets not denominated in cash (so ones denominated in other markets) don't count them towards topic popularity (because they're already counted in popularity in the eth denominated markets. Popularity should be open interest for a given topic in eth. 

- for market popularity for these markets we either should not count them, or count them using the value of the denomination token, which when the parent market is still trading is via best bid for that outcome token, and when it's resolved we can just check the resolution price. 

- also note not to charge reporting complete set fees on these markets (they're already charged once in the parent market), market creator fees can still be charged. The old develop branch did this but not sure if it's the case in this one or not

### Reproduction Steps
1. 2. 3. 4. 5. 

### Proposed Solution

**Comment by joeykrug** [comment]
Each branch has a sortedMarketsList contract associated with it


[3:18] 
Each market keeps track of which sortedMarketsList contract it is a part of


[3:20] 
If market.getBranch().getSortedMarketsList() == market.getShadySortedMarketsList() [i.e. the one the market thinks/claims it is a part of] all is good (edited)


[3:20] 
The UI checks that client side when a user clicks on or enters a trade in a market (edited)


[3:20] 
If they're not equal, that means there was a fork and this market was affected (i.e. it was on the branch that forked and ended up moving to a new branch)


[3:21] 
If that's the case, the market is removed from market.getShadySortedMarketsList() and added to the new list which is market.getBranch().getSortedMarketsList()


[3:22] 
It's added either using two "marketSortHints" which are optional parameters to the trade and/or make order functions


[3:22] 
Or just a separate function call entirely


[3:23] 
To prevent someone from maliciously moving it, on chain we would only allow it to switch lists in the scenario where `market.getBranch().getSortedMarketsList() != market.getShadySortedMarketsList()`


[3:24] 
The caveat of this is that there may be a small period of time when a market has just forked and is in the wrong list until someone interacts with it


[3:24] 
However this is a rare enough situation that I think that's a fine caveat/catch

**Comment by nuevoalex** [comment]
These notes are still relevant but will apply to the augur nodes now more so than the contract code base I think.

**Comment by joeykrug** [comment]
Ok closing then
