### ISSUE TITLE
Search and sort service-on-a-contract

### ISSUE THREAD

**Issue by tinybike** [AugurProject/augur-core#27]
Pre-loading all markets during the initial UI load will become prohibitively slow as the number of markets grows.  These are good candidates for services that could be provided as a separate contract: search/sort are read-only operations and can use `eth_call` "gas".

**Comment by joeykrug** [comment]
Probably would run up against the call gas limit very quickly which is a few hundred mil once there are enough markets, so going to close for now

**Comment by tinybike** [comment]
Is there actually a call gas limit?  I was under the impression you could set gas as high as you wanted for calls -- getMarketsInfo relies on that being true, actually...

**Comment by joeykrug** [comment]
Yeah there is, I've hit it a few times when testing. In the 100s of millions

**Comment by joeykrug** [comment]
I just looked at your code for get markets info

**Comment by joeykrug** [comment]
It doesn't look like it depends on that being true

**Comment by joeykrug** [comment]
As long as the offset isn't too big that is

**Comment by tinybike** [comment]
Good point, as long as offset/numMarketsToLoad are set appropriately it's fine even if there's a limit.  Is the tester's gas limit higher for call than for sendTransaction?

**Comment by joeykrug** [comment]
Yeah, although I don't remember the default. I know above a few hundred million it just ignores it and hits a gas limit anyway haha
