### ISSUE TITLE
Limit orders

### ISSUE THREAD

**Issue by tinybike** [AugurProject/augur-core#30]
Making an issue for this because why not

**Comment by joeykrug** [comment]
![Capture.PNG](https://files.zenhub.io/56aba7c012189dca2c5ee745)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by joeykrug** [comment]
![capture](https://cloud.githubusercontent.com/assets/5925937/12683518/58c02a8a-c67f-11e5-80d8-dd0f1132db06.PNG)

**Comment by joeykrug** [comment]
Did some work on this: [Orders.docx](https://files.zenhub.io/56b3bfb5eda2d4c659afcdaa)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by joeykrug** [comment]
New fee structure for when to charge on trades. MM pay no fees on her own trades. 
Let people know pending transactions and what orders have already been picked up in pending broadcasted transactions when looking at the book - remove those orders if the other side has already been taken in the transaction pool (those orders would get executed first on Ethereum anyway based on time precedence and default gas price). If not processed / taken up put those orders back on the book. 
If two orders at same price placed on the book, the one placed first should get executed first.

**Comment by joeykrug** [comment]
fix fees - can't pay a fee if <1 share atm b/c will round down to zero
