### ISSUE TITLE
Ls-lmsr sum trick

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur-core#34]
Use the log sum of exp trick to calculate ls-lmsr at higher numbers in the exp.

**Comment by joeykrug** [comment]
Not relevant anymore since msr will be calculated off chain in new order schema

**Comment by tinybike** [comment]
It's still relevant, it's just that now I have to implement the sum trick :P

**Comment by joeykrug** [comment]
You won't because you don't have limited exponential functions like serpent.  Unless the exp functions you can get in JavaScript are junk, idk

**Comment by tinybike** [comment]
The built-in math functions are pretty junky, but since there are nice libraries like https://github.com/MikeMcl/decimal.js/ around I guess you're right!
