### ISSUE TITLE
Upload verified source code to Etherscan for old token

### ISSUE THREAD

**Issue by dmdque** [AugurProject/augur-core#582]
The old [Augur token](https://etherscan.io/address/0x48c80f1f4d53d5951e5d5438b54cba84f29f32a5#code) doesn't have verified source code uploaded to Etherscan. Can you upload it as a favour to the dev community?

PS.
> When raising issues, follow the appropriate issue template in the root directory

I could not find any issue template.

**Comment by MicahZoltu** [comment]
@dmdque The original REP contract (no longer in use) was written in Serpent which can't be verified on etherscan.

**Comment by dmdque** [comment]
Wow, good to know. Can you link me to that source code? Thanks.

**Comment by MicahZoltu** [comment]
I looked around and no longer have a link.  The code is in this GitHub repository's history, and it should be present up until at least when we switched over Solidity contracts (which was summer 2017).
