### ISSUE TITLE
Some possible inconsistency in Map.sol

### ISSUE THREAD

**Issue by wlamos** [AugurProject/augur-core#724]
For a map data structure, it should satisfy:

    for every (key, value), if _add(key, value)_ returns true, we should have _contains(key)_ return true.

     But in this implementation, if value is 0, the above property is not satisfied.

**Comment by nuevoalex** [comment]
@wlamos That's fair. You're suggesting we add a `require(value != bytes32(0))` in the `add` method, right?

**Comment by wlamos** [comment]
Yes.

**Comment by adrake33** [comment]
Added ClubHouse ticket for this: https://app.clubhouse.io/augur/story/16250/add-require-statement-to-map-add-for-consistency

**Comment by adrake33** [comment]
Closing, as this has been added to v2 of the contracts.
