### ISSUE TITLE
Move expiry source and tags on-chain

### ISSUE THREAD

**Issue by tinybike** [AugurProject/augur-core#76]
I think we should move expiry source and tags on-chain, since these are both pretty central to the market (expiry source especially).  My suggestion is to include them on-contract (rather than in event logs) since retrieving on-contract data is significantly faster than looking up logs.

Since tags are text, for efficiency's sake it might make sense to limit them to 32 characters, so they can be stored as numbers.

**Comment by joeykrug** [comment]
If there are 10000 markets can you sort them faster by category tag by making calls through every possible market and getting the tags and then sorting them from there or calling to get the logs using filter for all markets tagged with politics?

**Comment by tinybike** [comment]
Using event logs is frankly not working at all at the moment; seeing if Parity will speed things up, but that's not a long-term solution.  I think it's safer for us to not store anything in logs (anything that needs to be on-chain should be on-contract).

**Comment by joeykrug** [comment]
done/added on forking branch w/ tags on chain and event res. source, once the forking stuff is done + on chain this'll be available
