### ISSUE TITLE
Incorrect Escrowed eth Value -displayed

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur-core#761]
Open Orders showed 17 eth escrowed for an order.  I cancelled the order but only recieved 15.3 eth back in my total balance.  Etherscan TX confirms 15.3 eth. The order was already partially traded on (so 15.3 was actually correct).  The problem is the open orders still displayed 17 eth escrowed. Should have updated to 15.3 (see third order down on screenshot)

![1-14scalar-cancel.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/30e8552d-bfd6-4062-8816-a44facae2a84)

 etherscan tx     0x7af0bcfbfb53d06a769d8fc12a2e3455ec16843de81757d04b6518b26ab9c3ab

occurred in augur app 1.9.0

**Comment by adrake33** [comment]
Issue moved to [AugurProject/augur #851](https://github.com/AugurProject/augur/issues/851) via [**ZenHub**](https://www.zenhub.com/)
