### ISSUE TITLE
Open Order does not remove after cancelled/Cancel just remains grayed out

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur-core#762]
After canceling an open order (which does go throw and the balance updates), the order remains in open orders, only "Cancel" is grayed out.

Order should be removed from open orders

See screenshot

![1-14scalar-cancel.jpg](https://images.zenhubusercontent.com/5c2f99aa80139b3816b48707/954c3ac8-ae23-4fc5-a24c-a78c4a126ea8)

**Comment by adrake33** [comment]
Issue moved to [AugurProject/augur #852](https://github.com/AugurProject/augur/issues/852) via [**ZenHub**](https://www.zenhub.com/)
