### ISSUE TITLE
Categorisation (Multiple categories) of Events using an standard key dictionary.

### ISSUE THREAD

**Issue by juanfranblanco** [AugurProject/augur-core#77]
I believe it will be ideal to categorised events, users will be interests will vary and event finding and filtering will be much easier. 

Not just that, but it will also allow for simpler localisation, data mining, etc.

I believe a data key dictionary standard could be use for everyone creating Dapps, so it might be also a good idea to have an standard. 
https://github.com/ethereum/EIPs/issues/81

**Comment by joeykrug** [comment]
Will include in issue #76
