### ISSUE TITLE
Allow market creators to update maker and taker fees

### ISSUE THREAD

**Issue by kevinday** [AugurProject/augur-core#94]
They can kind of do this now, but since updateTradingFee doesn't take the maker percentage as a param any tradingFee update has to keep the same maker/taker %.

Adding makerFee to updateTradingFee will allow market creators to update their maker/taker fees to whatever they want (as long as tradingFee < currentFee).

Is this something we want to support? If so I can add this, otherwise feel free to close.

**Comment by RonB7139** [comment]
Suggest follow Joey's lead on this as there was some decent discussion
behind the ultimate decision to allow creator to set maker/taker ratio
between 0% and .5% of base fee, where the discount was "paid" by the
taker....  RB

**Comment by joeykrug** [comment]
feel free to add as long as you check makerFee is between 0 and 50%

**Comment by kevinday** [comment]
ok, will do.

**Comment by joeykrug** [comment]
Done by Kevin above ^
